# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  web:
    #image: reactioncommerce/example-storefront:3.0.0
    image: reactioncommerce/node-dev:10.16.3-v2
    command: "./bin/start"
    volumes:
      - .:/usr/local/src/app
      - web-yarn:/home/node/.cache/yarn
      - empty_node_modules:/usr/local/src/app/node_modules
    env_file:
      - ./.env
    networks:
      default:
      reaction:
    ports:
      - 4000:4000

volumes:
  web-yarn:
  empty_node_modules:
